### ISSUE TITLE
Tag consistency for BLS/Schnorr signatures

### ISSUE THREAD

**Issue by tessico** [EspressoSystems/espresso-systems-common#7]
1. Most tags for Schnorr structs are not "Schnorr-explicit", e.g. the tag for signature struct is `SIG` while for BLS signature it's `BLSSIG`,  but the verification key is `SCHNORRVERKEY`. Should we add a prefix to **all** Schnorr specific ones too, for consistency? E.g. `SCHNORRSIG`?
2. BLS tags exist for signing key & verification key separately, but not for a keypair. In contrast, Schnorr has a `SIGNINGKEYPAIR` tag, but not `SCHNORRSIGKEY`. If we want to add trait bounds as [detailed here](https://github.com/EspressoSystems/jellyfish/issues/145), we'd need to derive add a tag for `SCHNORRSIGKEY` (no harm in leaving the keypair though, it's just an implementation difference in how BLS vs. Schnorr generate a keypair. For the same reason, I don't think we need to add a `BLSSIGNINGKEYPAIR` either right now).

@nyospe @alxiong @jbearer

**Comment by jbearer** [comment]
1. Yeah, we should be consistent. I don't have a strong opinion about whether we add the prefix everywhere or drop the prefix completely. Probably adding the prefix is slightly better for debugability.
2. Feel free to add tags to any and all types that don't have them, the more things are tagged the better
